import { gmail_v1 } from 'googleapis';
import { EmailSummary } from './processEmails';

/**
 * Sends a summary email with all processed emails
 */
export async function sendSummaryEmail(
  gmail: gmail_v1.Gmail,
  summaries: EmailSummary[],
  recipientEmail: string
): Promise<void> {
  try {
    const emailBody = formatSummaryEmail(summaries);
    const subject = `Email Summary - ${new Date().toLocaleDateString()}`;

    const message = [
      `To: ${recipientEmail}`,
      'Content-Type: text/html; charset=utf-8',
      'MIME-Version: 1.0',
      `Subject: ${subject}`,
      '',
      emailBody,
    ].join('\n');

    const encodedMessage = Buffer.from(message)
      .toString('base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

    await gmail.users.messages.send({
      userId: 'me',
      requestBody: {
        raw: encodedMessage,
      },
    });

    console.log('Summary email sent successfully');
  } catch (error) {
    console.error('Error sending summary email:', error);
    throw error;
  }
}

/**
 * Formats the email summaries into an HTML email body
 */
function formatSummaryEmail(summaries: EmailSummary[]): string {
  const priorityOrder = { high: 1, medium: 2, low: 3 };
  const sorted = summaries.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);

  const emailItems = sorted
    .map(
      (item) => `
    <div style="margin-bottom: 30px; padding: 15px; border-left: 4px solid ${getPriorityColor(item.priority)}; background-color: #f9f9f9;">
      <h3 style="margin-top: 0; color: #333;">${item.email.subject}</h3>
      <p style="color: #666; font-size: 14px;">
        <strong>From:</strong> ${item.email.from}<br>
        <strong>Date:</strong> ${item.email.date}<br>
        <strong>Priority:</strong> <span style="color: ${getPriorityColor(item.priority)}; font-weight: bold;">${item.priority.toUpperCase()}</span>
      </p>
      <p style="color: #333;"><strong>Summary:</strong> ${item.summary}</p>
      ${
        item.actionItems.length > 0
          ? `
      <p style="color: #333;"><strong>Action Items:</strong></p>
      <ul style="color: #333;">
        ${item.actionItems.map((action) => `<li>${action}</li>`).join('')}
      </ul>
      `
          : ''
      }
    </div>
  `
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Email Summary</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
    Email Summary - ${new Date().toLocaleDateString()}
  </h1>
  <p style="color: #666;">You have <strong>${summaries.length}</strong> email(s) to review:</p>
  ${emailItems}
  <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
  <p style="color: #999; font-size: 12px; text-align: center;">
    This is an automated summary generated by your Email Summarizer
  </p>
</body>
</html>
`;
}

/**
 * Returns a color code based on priority level
 */
function getPriorityColor(priority: 'high' | 'medium' | 'low'): string {
  const colors = {
    high: '#e74c3c',
    medium: '#f39c12',
    low: '#3498db',
  };
  return colors[priority];
}
